### ISSUE TITLE
Lombock annotations for setters and getters are throwing errors 

### ISSUE THREAD

**Issue by oruganti1289** [mrin9/Angular2_SpringBoot#1]
I'm learning spring boot and these annotations are throwing errors for all the setters and getters in the application, is it common or somthing wrong with the code

**Comment by mrin9** [comment]
Lombock annotations generate auto setters and getters. I used it to save myself from manually creating them.
 Did you happen to modify the code and create your own setters and getters ? in that case you will get a conflict. If you decide to create your own setters and getters then you should'nt use lombock. And if you didnt modify the code then please provide me the log of the error so that i can have a look

**Comment by oruganti1289** [comment]
I didn't modify any code, I just took a clone of the repository in eclipse and exported the project as gradle project. Build the front end  in npm and ran the angular boot, the front end opens up but doesn't work as the API is not working as there is problem with the setters and getters in the code
[errorlog.txt](https://github.com/mrin9/Angular2_SpringBoot/files/832181/errorlog.txt)
 Attached is the error log

**Comment by mrin9** [comment]
Well, I know that eclipse internally uses Lombok, but it is used when you explicitly state to generate getters and setters, and you mentioned that you didnt do it.
I never used this project on eclipse. But I just deployed and build this project on Heroku, and it is running fine there. you can access it [here](https://infomud.herokuapp.com/)
(since its a free deploy you might have to try to refresh couple of times )


can you just try to build it without importing into eclipse, it may be possible eclipse might be doing some magic.

So just clone and from the root folder

- 1. Navigate to webui and build the front-end  `ng build -prod -aot=false`
- 2. Then build the backend `gradle build` (the gradle script copy the frontend code to the tomcat container, so you must generate the frontend first)

meanwhile i will get through the log you provided me. but that will happen in  weekend

**Comment by mrin9** [comment]
Keeping it Open

**Comment by oruganti1289** [comment]
Got it solved, need to install lombok separately for eclipse, good job
