### ISSUE TITLE
ng serve -prod -aot

### ISSUE THREAD

**Issue by sgrillon14** [mrin9/Angular2_SpringBoot#14]
can you fixe aot build mode?

"scripts": {
    "ng": "ng",
    "start": "ng serve --aot",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },

**Comment by sgrillon14** [comment]
1st error:

Failed to compile.

```
Error at C:/workspace/POC/Angular-SpringBoot-REST-JWT-SGR/webui/src/app/home.component.html(35,10): Property 'subNav' does not exist on type '{ label: string; href: string; subNav: { label: string; href: string; }[]; } | { label: string; h...'.
  Property 'subNav' does not exist on type '{ label: string; href: string; }'.
Error at C:/workspace/POC/Angular-SpringBoot-REST-JWT-SGR/webui/src/app/home.component.html(35,10): Property 'subNav' does not exist on type '{ label: string; href: string; subNav: { label: string; href: string; }[]; } | { label: string; h...'.
  Property 'subNav' does not exist on type '{ label: string; href: string; }'.
```

**Comment by sgrillon14** [comment]
change:

```
public appHeaderItems=[
        {
            label   : 'Dashboard',
            href    : '/home/dashboard',
            subNav  : [
                { label:"Order Stats"  , href:"/home/dashboard/order"  },
                { label:"Product Stats", href:"/home/dashboard/product"}
            ]
        },
        { label: 'Orders'   , href: '/home/orders'},
        { label: 'Products' , href: '/home/products'},
        { label: 'Customers', href: '/home/customers'},
        { label: 'Employees', href: '/home/employees'}
    ];
```

by:

```
public appHeaderItems=[
        {
            label   : 'Dashboard',
            href    : '/home/dashboard',
            subNav  : [
                { label:"Order Stats"  , href:"/home/dashboard/order"  },
                { label:"Product Stats", href:"/home/dashboard/product"}
            ]
        },
        { label: 'Orders'   , href: '/home/orders'    , subNav: []},
        { label: 'Products' , href: '/home/products'  , subNav: []},
        { label: 'Customers', href: '/home/customers' , subNav: []},
        { label: 'Employees', href: '/home/employees' , subNav: []}
    ];
```

**Comment by sgrillon14** [comment]
2nd error:

![img_20171030_131834271](https://user-images.githubusercontent.com/5530550/32780579-16ecc0ce-c942-11e7-9f0d-44b985ed4730.jpg)

**Comment by sgrillon14** [comment]
2nd error:

![2017-11-14_134343](https://user-images.githubusercontent.com/5530550/32780601-33b51828-c942-11e7-8f10-d09bca49b20b.png)

**Comment by mrin9** [comment]
Hi @sgrillon14 , I fixed the above issues in the last commit. The console error that you showed is due to a 3rd party lib ```ngx-datatable```
You may track that issue  [here](https://github.com/swimlane/ngx-datatable/issues/1114)  

as an workaround for now, we need to avoid ```--prod``` flag while executing ```ng build```

I also updated the to Angular 5 and using the new ```httpclient``` module. can you give it a try let me know if things are working on your side. 
to build the frontend for now just use ``` ng build --aot=false```
If you confirm ...things are fine ...i will close this issue , thanks for testing it out letting me know abt the issues

**Comment by sgrillon14** [comment]
you can close this issue if you merge PR #15

if you have one minute, you can up vote to [stackoverflow](https://stackoverflow.com/questions/47273324/angular-5-aot-vs-angular-5-aot-false)

**Comment by mrin9** [comment]
i am sorry, not every error is due to ```ngx-datatable```
there are quite a few issues you can track  ```in angular-cli``` space specially after they changed the minification process from js-uglify to es-uglify

For all you know the guy may not be using ```ngx-datatable``` at all  in his project.
or cud have made the same mistake what ```ngx-datatable``` guys did , this is not clear from the question. i am sorry i cant up-vote on the answer. 
I knew whats exactly was the problem with this project ... but that shouldn't be the solution for everyone
