### ISSUE TITLE
is there a way of adding more than just two roles ?

### ISSUE THREAD

**Issue by yiss** [mrin9/Angular2_SpringBoot#23]
Hello,
It's actually not an issue but more of a question, for example I have an authenticated user than can post articles and comments and I want with Spring Security that the user has only access to his articles and his comments ? thank you

**Comment by mrin9** [comment]
Yes, you can have as many roles as you want. you got to add them [here](https://github.com/mrin9/Angular-SpringBoot-REST-JWT/blob/c346e82d155b0151bf350d1f67b898f745c7bea5/src/main/java/com/app/model/user/Role.java#L4)

Now it depends how you want to structure the user model. In this app an user can have only a single role It can either ADMIN or USER. but if you wish instead of accepting a single role you can have an user who can have multiple roles. for this you have to change the Role in user model to a list of Roles [here](https://github.com/mrin9/Angular-SpringBoot-REST-JWT/blob/c346e82d155b0151bf350d1f67b898f745c7bea5/src/main/java/com/app/model/user/User.java#L30)
change it to ``` List<Role> roles``` 

I am sorry i did-not get the use case that you mentioned above, but from your title it appears that you want to deal with multiple roles, and thats what I explained. 
Further if you want to authenticate which items belongs to which user, thats typically not done by roles. The jwt-token contains the userid or email of the user who is making the REST request and you can match this userid with the one stored in the db to confirm if he is allowed to update the item
