### ISSUE TITLE
Can't debug in eclipse due to compile issues related to properties

### ISSUE THREAD

**Issue by datasmithtech** [mrin9/Angular2_SpringBoot#42]
i can build & run solution, however, i can't debug using eclipse

errors appear related to properties when starting debug session.

any suggestions?

**Comment by mrin9** [comment]
I think eclipse allows you to run an external web-server on which you deploy/publish a java WebApp.
This Project contains its own embedded WebServer, So there is no `.war` file that gets deployed onto a Webserver.
    
It must be something to do with how you are trying to run this app in eclipse. 
check if this [stack overflow question](https://stackoverflow.com/questions/24113939/how-to-debug-spring-boot-application-with-eclipse) helps you

Since this aint an issue with this project, am closing this one
